name: gradle

on:
  schedule:
    - cron: '30 2 2 * *'
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test with Java ${{ matrix.jdk }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [ '8', '11', '17', '18' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.jdk }}
        cache: 'gradle'

    - name: Gradle Build
      run: ./gradlew check

    - name: Gradle Check
      run: ./gradlew check
